# Generated by Django 5.1.3 on 2024-11-11 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_notas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='turmas',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='turma',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='sistema_notas.turma'),
            preserve_default=False,
        ),
    ]
